print("\nWelcome to ABS 1!")
print("Hello " * 5 + "\n\n")
print("What's your name?\n")
yourName = input()
print("\nHello " + yourName)
nameFile = open('.experimentalOutputs/nameFile', 'w')
nameFile.write(yourName)
print("Your name has been recorded")